"""
Django settings for ddm project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j^_k2ze-^3)j^sk0h)u#8g=9vitr2g9x3*kisc4o9)jsi_r*9!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]

ADMINS = (
    ('maxijie', 'jay0289@163.com'),
)

EMAIL_HOST = 'smtp.qq.com'
# EMAIL_HOST = "pop.exmail.qq.com"
EMAIL_PORT = 465
# EMAIL_PORT = 587 465
EMAIL_HOST_USER = "1563786048@qq.com"
EMAIL_HOST_PASSWORD = "wnifegvsfrlwbagb"
EMAIL_USE_SSL = True
SERVER_EMAIL = "1563786048@qq.com"


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "bms",
)

CRONJOBS = [
    ('*/1 * * * *', 'bms.logics.consume.test',
        ">> %s" % os.path.join(BASE_DIR, 'logs/test_crontab.log')),
]

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'lib.djhelper.middleware.auth_middleware.AuthMiddleware',
)

ROOT_URLCONF = 'ddm.urls'

# TEMPLATE_DIRS = (
#     os.path.join(BASE_DIR, 'templates/'),
# )

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates').replace('\\', '/'),
                 "templates/cpts/", "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ddm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "ddm_server",
        'USER': "maxijie",
        'PASSWORD': "86202263jaY",
        'HOST': "rm-2ze67283o18nheg08.mysql.rds.aliyuncs.com",
        'PORT': 3306,
    }
}
"""
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'DEBUG',
        },
    }
}
"""

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

COOKIE_KEY = "FopGQ1C7gaIPJTPdOsLX"

SERVER_IP = "123.57.18.96"
SERVER_ROOT = "http://bi.bellcat.cn"
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
IMAGES_URL = "/static/images/"
IMAGES_ROOT = os.path.join(BASE_DIR, 'static/images/')
QRCODE_URL = "/static/images/qrcode/"
QRCODE_ROOT = os.path.join(BASE_DIR, 'static/images/qrcode/')
WECHAT_APPID = "wx8bbf0161ef2a6209"
WECHAT_AESKEY = "9lGuZLFVQw795105VstFopGQ1C7gaIPJTPdOsLX8FLM"
WECHAT_TOKEN = "bellcatwechat"
WECHAT_APPSECRET = "e1a57fd88bc1f94f5ffd2520add1beb9"
WECHAT_MCHID = "1355448002"
WECHAT_PAYKEY = "cDTOYt9aXfqS6wU02BpuneiExW135r7v"
DINGDANGMAO_QRCODE = "http://weixin.qq.com/r/fzo7I-7E-KODrbpA929t"
